# Generated by Django 5.1 on 2024-08-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Familias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigobarras', models.CharField(default=0, max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_precio', models.DateField()),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_stock', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.CharField(blank=True, max_length=250)),
                ('idempresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.familias')),
            ],
            options={
                'ordering': ['-activo', 'descripcion'],
            },
        ),
    ]
