# Generated by Django 5.1 on 2024-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_article_articulos_familias_idempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familias',
            options={'ordering': ['id'], 'verbose_name': 'Familias'},
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
