# Generated by Django 5.1 on 2024-08-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
