# Generated by Django 5.1 on 2024-08-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
    ]
