# Generated by Django 5.1 on 2024-08-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_clientes_tipomovimientos_articulos_dtoefectvo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formaspago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('credito', 'Tarjeta Credito'), ('debito', 'Tarjeta Debito'), ('contado', 'Efectivo'), ('transferencia', 'Transferencia/QR')], max_length=20)),
                ('aplicadto', models.BooleanField(default=0)),
                ('aplicargo', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='dtoefectvo',
        ),
        migrations.AddField(
            model_name='empresas',
            name='dtoefectvo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empresas',
            name='margen_emp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empresas',
            name='recargo_emp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tipomovimientos',
            name='mov_st_pr',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tipomovimientos',
            name='tipo',
            field=models.CharField(choices=[('entradast', 'Compra'), ('salidast', 'Venta'), ('regulast', 'Regularizacion Stock'), ('traspado', 'Traspaso empresas'), ('subaprecio', 'Subir Precio'), ('bajaprecio', 'Bajar Precio')], max_length=20),
        ),
        migrations.CreateModel(
            name='cabecera_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechav', models.DateField()),
                ('nomcliente', models.CharField(default='', max_length=50)),
                ('dtoeftvo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('otrodto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recargo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('imptotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
                ('formapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.formaspago')),
            ],
        ),
        migrations.CreateModel(
            name='hist_movart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamov', models.DateField()),
                ('numdoc', models.CharField(default=0, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('precioactual', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('porprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nuevoprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('stockactual', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('nuevostock', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articulos')),
                ('tipomov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipomovimientos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
