# Generated by Django 5.1 on 2024-09-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_formaspago_remove_articulos_dtoefectvo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomovimientos',
            name='mov_st_pr',
        ),
        migrations.RemoveField(
            model_name='tipomovimientos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipomovimientos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipomovimientos',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('traspaso_entrada', 'Traspaso desde'), ('venta', 'Venta'), ('traspaso_salida', 'Traspaso a'), ('ajuste', 'Ajuste de stock')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='hist_movart',
            name='tipomov',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipomovimientos',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('regularizacion', 'Regularización')], max_length=20),
        ),
    ]
