# Generated by Django 5.1 on 2024-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_tipomovimientos_mov_st_pr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='linea1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='linea2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='linea3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='linea4',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='linea5',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='venta',
            field=models.BooleanField(default=True),
        ),
    ]
