# Generated by Django 5.1 on 2024-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_empresas_linea1_empresas_linea2_empresas_linea3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='linea1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='linea2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='linea3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='linea4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='linea5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
