# Generated by Django 5.1 on 2024-09-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_empresas_linea1_alter_empresas_linea2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
    ]
