# Generated by Django 5.1 on 2024-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_clientes_apellido_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
