# Generated by Django 5.1 on 2024-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera_venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
