# Generated by Django 5.1 on 2024-09-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cabecera_venta_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabecera_venta',
            name='nomcliente',
        ),
        migrations.AlterField(
            model_name='cabecera_venta',
            name='cliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
