# Generated by Django 5.1 on 2024-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_cabecera_venta_nomcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='margen2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
