# Generated by Django 5.1 on 2024-10-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_articulos_margen2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['-activo', 'familia', 'descripcion']},
        ),
        migrations.AddField(
            model_name='cabecera_venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
