# Generated by Django 5.1 on 2024-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_articulos_options_cabecera_venta_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecera_venta',
            name='fechav',
            field=models.DateTimeField(),
        ),
    ]
