# Generated by Django 5.1.4 on 2025-04-15 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen_cloud',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
