# Generated by Django 5.1.4 on 2025-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_articulos_imagen_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='imagenes',
            field=models.BooleanField(default=False),
        ),
    ]
