# Generated by Django 5.1.4 on 2025-08-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_empresas_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecera_venta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='hist_movart',
            name='fechamov',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
