# Generated by Django 5.1.4 on 2025-08-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cabecera_venta_empresa_alter_hist_movart_fechamov'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_movart',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
    ]
